# Generated by Django 2.2.1 on 2019-07-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='theme',
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=1000)),
                ('book_id', models.ForeignKey(db_column='Book.id', on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
    ]
