# Generated by Django 2.2.1 on 2019-07-28 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('lookup', models.IntegerField(default=0)),
                ('context', models.TextField()),
                ('bookName', models.ForeignKey(db_column='Book.id', on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('board_id', models.ForeignKey(db_column='Board.id', on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('user_id', models.ForeignKey(db_column='User.user_id', on_delete=django.db.models.deletion.CASCADE, to='signup.User')),
            ],
        ),
    ]
