# Generated by Django 2.2.1 on 2019-07-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_user_name'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=500)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.Board')),
                ('user_id', models.ForeignKey(db_column='User.user_id', on_delete=django.db.models.deletion.CASCADE, to='signup.User')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
